import { defaultSchema } from "rehype-sanitize";

export const MARKDOWN_SANITIZE_SCHEMA = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "div",
    "img",
    "input",
    "section",
    "sup",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "del",
    "hr",
    "dl",
    "dt",
    "dd",
  ],
  attributes: {
    ...(defaultSchema.attributes ?? {}),
    a: [
      ...(defaultSchema.attributes?.a ?? []),
      "href",
      "title",
      "id",
      "className",
      "dataFootnoteRef",
      "ariaDescribedBy",
    ],
    div: ["id", "className"],
    h2: [...(defaultSchema.attributes?.h2 ?? []), "id", "className"],
    img: ["src", "alt", "title"],
    input: ["type", "checked", "disabled"],
    li: [...(defaultSchema.attributes?.li ?? []), "className"],
    section: ["className", "dataFootnotes"],
    sup: ["className"],
    th: ["align"],
    td: ["align"],
    ul: [...(defaultSchema.attributes?.ul ?? []), "className"],
  },
  protocols: {
    ...(defaultSchema.protocols ?? {}),
    href: ["https"],
    src: ["https"],
    cite: ["https"],
  },
};